### ISSUE TITLE
Old Linux kernel series (5.10) is used

### ISSUE THREAD

**Issue by paulmenzel** [sonic-net/sonic-linux-kernel#314]
Are there any plans to move to Linux 6.1? I guess, when SONiC moves the Debian “base image” to *bookworm*, which is currently testing?

**Comment by saiarcot895** [comment]
Yes, when bookworm gets officially released and SONiC moves to bookworm, the master branch of this repo will move to 6.1.

**Comment by MalteJ** [comment]
Debian 12.0 was released on [June 10th, 2023](https://www.debian.org/News/2023/20230610).

https://www.debian.org/releases/bookworm/#:~:text=Debian%2012.0%20was%20released%20on,page%20and%20the%20Installation%20Guide.

**Comment by saiarcot895** [comment]
Master branch is now on Linux 6.1.
